# Generated by Django 5.1.6 on 2025-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_job_category_alter_job_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior Level"),
                ],
                default="entry",
                max_length=10,
            ),
        ),
    ]
